root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/jobs-service ./cmd/jobs-service"
  bin = "./tmp/jobs-service"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "e2e"]
  delay = 500
  stop_on_error = true
  send_interrupt = true
  kill_delay = 2000

[log]
  time = false
  main_only = true
